### ISSUE TITLE
[IDEA] Add Support with Subfolder and Other Wiki Names

### ISSUE THREAD

**Issue by kookma** [K4rian/twserver-go#2]
First many thanks for this amazing portable tool!

Two suggestion:
1. support subfolders for Tiddlywikis
2. support for other names e.g (mywiki.html instead of index.html)

The subfolder can be set up and used but backup does not work!

**Comment by kookma** [comment]
I see the new version supports other name for index file.
But why it can not serve multiple .html from www folder?
I mean if you put doc.html tw.html, ...
then `http://localhost:8080/doc.html` should work! but now it returns: `Invalid URL:`

**Comment by K4rian** [comment]
Hi,

> I see the new version supports other name for index file.
>
It's been the case since the very first release. Subfolders are also supported as specified in the [README](
https://github.com/K4rian/twserver-go#customizing).

> But why it can not serve multiple .html from www folder?
>
You can serve any index file by putting it in a custom directory as shown in the readme (see the link above).
The server can only serves 1 wiki per instance though.
If you want to host multiple wikis, you can use the provided [docker](https://github.com/K4rian/docker-twserver) file to deploy as many server as needed.

> The subfolder can be set up and used but backup does not work!
>
Only the wiki itself is archived by the server; I'm afraid you have to rely on an external service (or script) for backing up the extra resources. Compressing everything after each modification could slow down the server and make it unresponsive (especially if there are a lot of files to take care of).

Hope this helps.

**Comment by kookma** [comment]
Thank you for explanation!
